### ISSUE TITLE
v2.3.1 connection pool can not release?

### ISSUE THREAD

**Issue by mbossX** [SAP/olingo-jpa-processor-v4#442]
error with v2.3.1, work fine with v2.2.0.

datasource config:
```yaml
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DB}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 6000
      connection-test-query: SELECT 1
```

odataconfig
```java
@Configuration
public class OdataConfig {
    @Bean
    public JPAODataSessionContextAccess sessionContext(@Autowired final EntityManagerFactory emf)
            throws ODataException {

        return JPAODataServiceContext.with()
                .setPUnit("odata")
                .setEntityManagerFactory(emf)
                .setTypePackage("com.jdjinsui.*")
                .setRequestMappingPath("/odata")
                .setEdmNameBuilder(new APINameBuilder("odata"))
                .setErrorProcessor(new OdataErrorProcessor())
                .build();
    }

    @Bean
    @Scope(scopeName = SCOPE_REQUEST)
    public JPAODataRequestContext requestContext() {

        return JPAODataRequestContext.with()
                .setCUDRequestHandler(new JPAExampleCUDRequestHandler())
//                .setDebugSupport(new DefaultDebugSupport())
                .build();
    }
}
```

run app, query some entity 10 times, get error:
```
org.hibernate.engine.jdbc.spi.SqlExceptionHelper: HikariPool-1 - Connection is not available, request timed out after 6006ms (total=5, active=5, idle=0, waiting=0)
```

view connect from db, get result:
```
SELECT ROW_NUMBER() OVER(ORDER BY pid) as rown,state,query FROM pg_stat_activity WHERE datname='gsm'
```
```
rown	state	query
1	active	SELECT ROW_NUMBER() OVER(ORDER BY pid) as rown,state,query FROM pg_stat_activity WHERE datname='gsm'
  2	idle	SELECT c.conkey FROM pg_constraint c WHERE c.contype = 'p' and c.conrelid = 12222
3	idle	/* <criteria> */ select m1_0.pid,m1_0.name,m1_0.id from sys_menu m1_0
4	idle	/* <criteria> */ select m1_0.pid,m1_0.name,m1_0.id from sys_menu m1_0
5	idle	/* <criteria> */ select count(r1_0.id) from sys_role r1_0
6	idle	/* <criteria> */ select r1_0.comment,r1_0.name,r1_0.update_time,r1_0.pid,r1_0.id,r1_0.create_time from sys_role r1_0
7	idle	/* <criteria> */ select count(u1_0.id) from sys_user u1_0
```
